export const URL = {
  GET_CAR: "cars/getallcars",
  LOGIN: "users/login",
  REGISTER: "users/register",
  BOOKING: "/bookings/bookcar",
  LISTBOOKINGS: "/bookings/getallbookings",
  CHART_BOOKING: "/bookings/data-chart",
  DELETE_BOOKING: "bookings/delete",
  ALL_AUTOMAKER: "/automakers/getall",
  DATA_TOTAL: "/cars/total",
  ADD_CAR: "cars/add-car",
  CREATE_CAR: "cars/create",
  EDIT_CAR: "cars/edit-car",
  UPDATE_CAR: "cars/update",
  DELETE_CAR: "cars/delete",
  GET_CAR_USER: "cars/user-car",
  APPROVE_CAR: "cars/approve",
  HIDE_SHOW_CAR: "cars/hideshow",
  ALL_USER: "users/getall",
  UPDATE_USER: "users/edit-user",
  DELETE_USER: "users/delete-user",
  ALL_CATEGORY: "categorys/getall",
  UPDATE_AUTOMAKER: "automakers/edit-automaker",
  DELETE_AUTOMAKER: "automakers/delete-automaker",
  CREATE_AUTOMAKER: "automakers/create",
  CREATE_BOOKING: "/bookings/bookingcar",
  UPDATE_STATUS: "/bookings/update-status",
  STATUS_APPROVE: "/bookings/status-approve",
  GET_ONE_CAR: "cars/get-one",
  CREATE_BLOG_CATEGORY: "blog-category/create",
  UPDATE_BLOG_CATEGORY: "blog-category/update",
  DELETE_BLOG_CATEGORY: "blog-category/delete",
  GET_ALL_BLOG_CATEGORY: "blog-category/get-all",
  CREATE_BLOG: "blogs/create",
  GET_ALL_BLOG: "blogs/get-all",
  UPDATE_BLOG: "blogs/update",
  GET_ONE_BLOG: "blogs/get-one",
  DELETE_BLOG: "blogs/delete",
  GET_ALL_PROVIDER: "providers/get-all",
  GET_BOOKING_OWNER: "bookings/get-booking/by-owner",
  UPDATE_BOOKING: "bookings/update",
  UPDATE_PROFILE: "users/edit-profile",
};
export const LIMIT = 9;
export const URL_LOCAL = "http://localhost:5000/";
