export const URL = {
  GET_CAR: "cars/getallcars",
  LOGIN: "users/login",
  REGISTER: "users/register",
  BOOKING: "/bookings/bookcar",
  LISTBOOKINGS: "/bookings/getallbookings",
  ALL_AUTOMAKER: "/automakers/getall",
  ADD_CAR: "cars/add-car",
  EDIT_CAR: "cars/edit-car",
  DELETE_CAR: "cars/delete-car",
  ALL_USER: "users/getall",
  UPDATE_USER: "users/edit-user",
  DELETE_USER: "users/delete-user",
  ALL_CATEGORY: "categorys/getall",
  UPDATE_AUTOMAKER: "automakers/edit-automaker",
  DELETE_AUTOMAKER: "automakers/delete-automaker",
  CREATE_AUTOMAKER: "automakers/create",
  CREATE_BOOKING: "/bookings/bookingcar",
  UPDATE_STATUS: "/bookings/update-status",
  GET_ONE_CAR: "cars/get-one",
};
export const LIMIT = 9;
